version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CCLab6

    ports:
      - "3310:3306"
    volumes:
      - lab7database:/var/lib/mysql

  lab7fastapi:
    image: lab7fastapi:latest
    container_name: lab7fastapi
    restart: always
    ports:
      - "8080:8080"

volumes:
  lab7database: